version: "3.6"
services:
    hipstore:
        image: hipstore
        build: hipstore
        ports:
            - "7878:7878"
        volumes:
            - "./hipstore/main:/root/main"
            - "./hipstore/users/:/root/users/"
        restart: always
    loli:
        image: loli
        build: loli
        ports:
            - "4242:4242"
        volumes:
            - "./loli/:/loli/"
        restart: always
    wroteup:
        image: wroteup
        build: wroteup
        ports:
            - "50000:50000"
        volumes:
            - "./wroteup/db.db:/go/src/github.com/kappactf/spbctf-20190303/services/wroteup/db.db"
        restart: always
    kappabonus:
        image: kappabonus
        build: kappabonus
        ports:
            - "3377:3377"
        restart: always

