version: "2.4"
services:
    hipstore:
        image: hipstore
        build: hipstore
        ports:
            - "7878:7878"
        volumes:
            - "./hipstore/users/:/root/users/"
        restart: always
        mem_limit: 500m
        pids_limit: 50
    loli:
        image: loli
        build: loli
        ports:
            - "4242:4242"
        volumes:
            - "./loli/data/:/loli/"
            - "./loli/data/users:/loli/users"
        restart: always
        mem_limit: 500m
    wroteup:
        image: wroteup
        build: wroteup
        ports:
            - "50000:50000"
        volumes:
            - "./wroteup/db.db:/go/src/github.com/kappactf/spbctf-20190303/services/wroteup/db.db"
        restart: always
        mem_limit: 500m
    kappabonus:
        image: kappabonus
        build: kappabonus
        volumes:
            - "./kappabonus/config.ini:/app/config.ini"
        ports:
            - "3377:3377"
        restart: always
        mem_limit: 500m


